---
driver:
  name: docker

transport:
  name: docker

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  hiera_data_path: hieradata
  require_chef_for_busser: false
#  puppet_version: '4.10.5'
#  puppet_yum_collections_repo: 'https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm'
  require_puppet_collections: false
#  hiera_config_path: hiera.yaml
  custom_options: --hiera_config /tmp/kitchen/hiera.yaml
  #require_puppet_repo: false

platforms:
  - name: puppet_master
    driver:
      image: ubuntu
      platform: ubuntu
      network:
        - ["private_network", {ip: "192.168.33.10"}]
        - ["forwarded_port", {guest: 6556, host: 9001}]
      customize:
        memory: 2048
    provisoner:
      custome_install_command: |
        sudo yum install puppet -y
  - name: check_mk_server
    driver:
      image: ubuntu
      platform: ubuntu
      network:
        - ["private_network", {ip: "192.168.33.20"}]
        - ["forwarded_port", {guest: 80, host: 9000}]
    provisioner:
      custom_install_command: |
        sudo sh -c "echo '192.168.33.10 default-puppet-master.vagrantup.com puppet' >> /etc/hosts"
        #        sudo yum install puppet -y
      puppet_apply_command: 'sudo -E /opt/puppetlabs/bin/puppet agent --test --waitforcert 30'
      puppet_verbose: true
      puppet_server: default-puppet-master.vagrantup.com
  - name: server_ubuntu_20.04
    driver:
      image: ubuntu:focal
      platform: ubuntu
      network:
        - ["private_network", {ip: "192.168.33.21"}]
        - ["forwarded_port", {guest: 80, host: 9001}]
    provisioner:
      custom_install_command: |
        sudo sh -c "echo '192.168.33.10 default-puppet-master.vagrantup.com puppet' >> /etc/hosts"
      puppet_apply_command: 'sudo -E /opt/puppetlabs/bin/puppet agent --test --waitforcert 30'
      puppet_verbose: true
      puppet_server: default-puppet-master.vagrantup.com
  - name: server_ubuntu_22.04
    driver:
      image: ubuntu:jammy
      platform: ubuntu
      network:
        - ["private_network", {ip: "192.168.33.22"}]
        - ["forwarded_port", {guest: 80, host: 9002}]
    provisioner:
      custom_install_command: |
        sudo sh -c "echo '192.168.33.10 default-puppet-master.vagrantup.com puppet' >> /etc/hosts"
      puppet_apply_command: 'sudo -E /opt/puppetlabs/bin/puppet agent --test --waitforcert 30'
      puppet_verbose: true
      puppet_server: default-puppet-master.vagrantup.com
  - name: client_centos-7
    driver:
      image: centos:7
      platform: centos
      network:
        - ["private_network", {ip: "192.168.33.30"}]
    provisioner:
      custom_install_command: |
        sudo sh -c "echo '192.168.33.10 default-puppet-master.vagrantup.com puppet' >> /etc/hosts"
      puppet_apply_command: 'sudo -E /opt/puppetlabs/bin/puppet agent --test --waitforcert 30'
      puppet_verbose: true
      puppet_server: default-puppet-master.vagrantup.com
#  - name: client_centos-8
#    driver:
#      image: centos:8
#      platform: centos
#      network:
#        - ["private_network", {ip: "192.168.33.40"}]
#    provisioner:
#      custom_install_command: |
#        sudo sh -c "echo '192.168.33.10 default-puppet-master.vagrantup.com puppet' >> /etc/hosts"
#      puppet_apply_command: 'sudo -E /opt/puppetlabs/bin/puppet agent --test --waitforcert 30'
#      puppet_verbose: true
#      puppet_server: default-puppet-master.vagrantup.com
  - name: client_rockylinux
    driver:
      image: rockylinux:9
      platform: rockylinux
      network:
        - ["private_network", {ip: "192.168.33.50"}]
    provisioner:
      custom_install_command: |
        sudo sh -c "echo '192.168.33.10 default-puppet-master.vagrantup.com puppet' >> /etc/hosts"
      puppet_apply_command: 'sudo -E /opt/puppetlabs/bin/puppet agent --test --waitforcert 30'
      puppet_verbose: true
      puppet_server: default-puppet-master.vagrantup.com

suites:
  - name: default
    manifests: site.pp

verifier:
  ruby_bindir: '/usr/bin'
